package model;

import java.util.Date;

/**
 * MODEL CLASS: IssueReceipt
 * Represents an issue receipt generated by the librarian.
 */
public class IssueReceipt {

    private int    receiptId;
    private int    requestId;
    private String receiptNumber;
    private Date   generatedDate;
    private Date   dueDate;
    private String approvalStatus;

    public IssueReceipt() {}

    public IssueReceipt(int receiptId, int requestId, String receiptNumber, Date generatedDate, Date dueDate, String approvalStatus) {
        this.receiptId = receiptId;
        this.requestId = requestId;
        this.receiptNumber = receiptNumber;
        this.generatedDate = generatedDate;
        this.dueDate = dueDate;
        this.approvalStatus = approvalStatus;
    }

    public int getReceiptId() { return receiptId; }
    public void setReceiptId(int receiptId) { this.receiptId = receiptId; }

    public int getRequestId() { return requestId; }
    public void setRequestId(int requestId) { this.requestId = requestId; }

    public String getReceiptNumber() { return receiptNumber; }
    public void setReceiptNumber(String receiptNumber) { this.receiptNumber = receiptNumber; }

    public Date getGeneratedDate() { return generatedDate; }
    public void setGeneratedDate(Date generatedDate) { this.generatedDate = generatedDate; }

    public Date getDueDate() { return dueDate; }
    public void setDueDate(Date dueDate) { this.dueDate = dueDate; }

    public String getApprovalStatus() { return approvalStatus; }
    public void setApprovalStatus(String approvalStatus) { this.approvalStatus = approvalStatus; }
}
