package model;

import java.util.Date;

/**
 * MODEL CLASS: ReturnReceipt
 * Represents a return receipt generated by the librarian.
 */
public class ReturnReceipt {

    private int    receiptId;
    private int    requestId;
    private String receiptNumber;
    private Date   generatedDate;
    private double fineAmount;
    private String returnStatus;

    public ReturnReceipt() {}

    public ReturnReceipt(int receiptId, int requestId, String receiptNumber, Date generatedDate, double fineAmount, String returnStatus) {
        this.receiptId = receiptId;
        this.requestId = requestId;
        this.receiptNumber = receiptNumber;
        this.generatedDate = generatedDate;
        this.fineAmount = fineAmount;
        this.returnStatus = returnStatus;
    }

    public int getReceiptId() { return receiptId; }
    public void setReceiptId(int receiptId) { this.receiptId = receiptId; }

    public int getRequestId() { return requestId; }
    public void setRequestId(int requestId) { this.requestId = requestId; }

    public String getReceiptNumber() { return receiptNumber; }
    public void setReceiptNumber(String receiptNumber) { this.receiptNumber = receiptNumber; }

    public Date getGeneratedDate() { return generatedDate; }
    public void setGeneratedDate(Date generatedDate) { this.generatedDate = generatedDate; }

    public double getFineAmount() { return fineAmount; }
    public void setFineAmount(double fineAmount) { this.fineAmount = fineAmount; }

    public String getReturnStatus() { return returnStatus; }
    public void setReturnStatus(String returnStatus) { this.returnStatus = returnStatus; }
}
